[package]
authors = ["Crypto Garage"]
name = "bitcoin-test-utils"
version = "0.1.0"

[dependencies]
bitcoin = {workspace = true}
bitcoincore-rpc = {version = "0.16"}
bitcoincore-rpc-json = {version = "0.16"}
