[package]
authors = ["Crypto Garage"]
description = "Creation, signing and verification of Discreet Log Contracts (DLC) transactions."
homepage = "https://github.com/p2pderivatives/rust-dlc"
license-file = "../LICENSE"
name = "dlc"
repository = "https://github.com/p2pderivatives/rust-dlc/tree/master/dlc"
version = "0.3.0"

[dependencies]
bitcoin = {workspace = true}
miniscript = "8.0.0"
secp256k1-sys = {workspace = true}
secp256k1-zkp = {workspace = true, features = ["bitcoin_hashes", "rand-std"]}
serde = {version = "1.0", default-features = false, optional = true}

[features]
# for benchmarks
unstable = []
use-serde = ["serde", "secp256k1-zkp/use-serde"]

[dev-dependencies]
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
bitcoincore-rpc = {version = "0.16.0"}
bitcoincore-rpc-json = {version = "0.16.0"}
dlc-trie = {path = "../dlc-trie"}
rayon = "1.5"
secp256k1-zkp = {workspace = true, features = ["bitcoin_hashes", "rand", "rand-std", "serde", "global-context"]}
