[package]
authors = ["Crypto Garage"]
edition = "2018"
name = "mocks"
version = "0.1.0"

[dependencies]
bitcoin = {workspace = true}
dlc = {path = "../dlc"}
dlc-manager = {path = "../dlc-manager"}
dlc-messages = {version = "0.3.0", path = "../dlc-messages"}
lightning = {workspace = true}
secp256k1-zkp = {workspace = true, features = ["bitcoin_hashes", "rand", "rand-std"]}
simple-wallet = {path = "../simple-wallet"}
